version: '3.8'

volumes:
  pg_data:
  media:
  static:

services:
  db:
    container_name: postgres_db
    image: postgres:13
    restart: always
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    build: ../
    env_file: ../.env
    restart: always
    volumes:
      - static:/backend_static
      - media:/app/media
  nginx:
    build: ./nginx
    depends_on:
      - backend
    volumes:
      - static:/staticfiles/
      - media:/media
    ports:
      - 8000:80 
